name: Probe Workflow Check

on:
  push:
    branches: [ main, master, "add/*" ]
  pull_request:
    branches: [ main, master, "add/*" ]

jobs:
  linters-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install ruff pytest

      - name: Run Ruff
        run: ruff check .

      - name: Check Ruff Formatting
        run: ruff format --check .

      - name: Run Pytest
        run: python -m pytest scripts/

  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --only-verified